### ISSUE TITLE
[ERROR] Failed to execute goal org.codehaus.mojo:exec-maven-plugin:3.0.0:java (default-cli) on project Translator

### ISSUE THREAD

**Issue by Gasu16** [Gasu16/Bpmn2Drools#1]
Sto avendo questo problema, non riesce a effettuare la transazione in un tempo prefixed di 600 secondi.

Ecco i log dell'errore

> An exception occured while executing the Java class. Transaction receipt was not generated after 600 seconds for transaction: 0x7a9d1267b2029d65ca955f1b4b30b94aaedc6b318e93dcc16afeab788f0c2aae -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoExecutionException

**Comment by matteotoma98** [comment]
fixato, era colpa della rete di Rinkeby.
